/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.ArticleEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<ArticleEntity, Integer> implements ArticlePersistence {
	
	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(ArticleEntity.class);
	}

	@Override
	public ArticleEntity load( Integer ref ) {
		return super.load( ref );
	}

	@Override
	public boolean delete( Integer ref ) {
		return super.delete( ref );
	}

	@Override
	public boolean delete(ArticleEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getRef() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ArticleEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
