/*
 * Created on 31 oct. 2017 ( Time 18:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.DatereservationEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.DatereservationPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Datereservation" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class DatereservationPersistenceJPA extends GenericJpaService<DatereservationEntity, Integer> implements DatereservationPersistence {

	/**
	 * Constructor
	 */
	public DatereservationPersistenceJPA() {
		super(DatereservationEntity.class);
	}

	@Override
	public DatereservationEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(DatereservationEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("DatereservationEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
