/*
 * Created on 3 nov. 2017 ( Time 10:20:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.PanieritemEntity;
import org.demo.bean.jpa.UtilisateurEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.PanieritemPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Panieritem" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PanieritemPersistenceJPA extends GenericJpaService<PanieritemEntity, Integer> implements PanieritemPersistence {
	
	/**
	 * Constructor
	 */
	public PanieritemPersistenceJPA() {
		super(PanieritemEntity.class);
	}

	@Override
	public PanieritemEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(PanieritemEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PanieritemEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}
	
	public List<PanieritemEntity> getPanierFromUser(int userid){
		
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PanieritemEntity.getPanierFromUser");
				query.setParameter("id", userid);
				
				List<PanieritemEntity> panier;
				try {
					panier = query.getResultList();
				}catch (NoResultException e){
					return null;
				}
				return panier;
			}
		} ;
		// JPA operation execution 
		return (List<PanieritemEntity>) execute(operation);
	}

	@Override
	public void cleanPanier(int userid) {
		JpaOperation operation = new JpaOperation() {
			List<PanieritemEntity> panier = getPanierFromUser(userid);
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				em.getTransaction().begin();
				for(PanieritemEntity p:panier) {
					p = em.merge(p);
					em.remove(p);
				}
				em.getTransaction().commit();				
				return true;
			}
		} ;
		// JPA operation execution 
		execute(operation);

	}

	@Override
	public PanieritemEntity searchItemInPänier(int userid, int articleref) {
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PanieritemEntity.searchItemInPanier");
				query.setParameter("id", userid);
				query.setParameter("ref", articleref);
				
				PanieritemEntity item;
				
				try {
					item = (PanieritemEntity) query.getSingleResult();
				}catch (NoResultException e){
					return null;
				}
				return item;
			}
		} ;
		// JPA operation execution 
		return (PanieritemEntity) execute(operation);
	}

}
