/*
 * Created on 31 oct. 2017 ( Time 18:39:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.TypeRessourceEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.TypeRessourcePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "TypeRessource" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypeRessourcePersistenceJPA extends GenericJpaService<TypeRessourceEntity, String> implements TypeRessourcePersistence {

	/**
	 * Constructor
	 */
	public TypeRessourcePersistenceJPA() {
		super(TypeRessourceEntity.class);
	}

	@Override
	public TypeRessourceEntity load( String type ) {
		return super.load( type );
	}

	@Override
	public boolean delete( String type ) {
		return super.delete( type );
	}

	@Override
	public boolean delete(TypeRessourceEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getType() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TypeRessourceEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
