/*
 * Created on 31 oct. 2017 ( Time 18:39:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.UtilisateurEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.UtilisateurPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Utilisateur" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UtilisateurPersistenceJPA extends GenericJpaService<UtilisateurEntity, String> implements UtilisateurPersistence {

	/**
	 * Constructor
	 */
	public UtilisateurPersistenceJPA() {
		super(UtilisateurEntity.class);
	}

	@Override
	public UtilisateurEntity load( String login ) {
		return super.load( login );
	}

	@Override
	public boolean delete( String login ) {
		return super.delete( login );
	}

	@Override
	public boolean delete(UtilisateurEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getLogin() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UtilisateurEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
