/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ARTICLE", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ArticleEntity.countAll", query="SELECT COUNT(x) FROM ArticleEntity x" )
} )
public class ArticleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="REF", nullable=false)
    private Integer    ref          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", length=200)
    private String     nom          ;

    @Column(name="PRIX")
    private Float      prix         ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="article", targetEntity=StockEntity.class)
    private List<StockEntity> listOfStock ;

    @OneToMany(mappedBy="article", targetEntity=PanieritemEntity.class)
    private List<PanieritemEntity> listOfPanieritem;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ArticleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRef( Integer ref ) {
        this.ref = ref ;
    }
    public Integer getRef() {
        return this.ref;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRIX ( REAL ) 
    public void setPrix( Float prix ) {
        this.prix = prix;
    }
    public Float getPrix() {
        return this.prix;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfStock( List<StockEntity> listOfStock ) {
        this.listOfStock = listOfStock;
    }
    public List<StockEntity> getListOfStock() {
        return this.listOfStock;
    }

    public void setListOfPanieritem( List<PanieritemEntity> listOfPanieritem ) {
        this.listOfPanieritem = listOfPanieritem;
    }
    public List<PanieritemEntity> getListOfPanieritem() {
        return this.listOfPanieritem;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(ref);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(prix);
        return sb.toString(); 
    } 

}
