/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "PANIERITEM"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PANIERITEM", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PanieritemEntity.countAll", query="SELECT COUNT(x) FROM PanieritemEntity x" ),
  @NamedQuery ( name="PanieritemEntity.getPanierFromUser", query="SELECT p FROM PanieritemEntity p WHERE p.utilisateur.id=:id"),
  @NamedQuery ( name="PanieritemEntity.cleanPanier", query="DELETE FROM PanieritemEntity p WHERE p.utilisateur.id=:id"),
  @NamedQuery ( name="PanieritemEntity.searchItemInPanier", query="SELECT p FROM PanieritemEntity p WHERE p.article.ref=:ref AND p.utilisateur.id=:id")
} )
public class PanieritemEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="QTE")
    private Integer    qte          ;

	// "userid" (column "USERID") is not defined by itself because used as FK in a link 
	// "articleref" (column "ARTICLEREF") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="USERID", referencedColumnName="ID")
    private UtilisateurEntity utilisateur ;

    @ManyToOne
    @JoinColumn(name="ARTICLEREF", referencedColumnName="REF")
    private ArticleEntity article     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PanieritemEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : QTE ( INTEGER ) 
    public void setQte( Integer qte ) {
        this.qte = qte;
    }
    public Integer getQte() {
        return this.qte;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUtilisateur( UtilisateurEntity utilisateur ) {
        this.utilisateur = utilisateur;
    }
    public UtilisateurEntity getUtilisateur() {
        return this.utilisateur;
    }

    public void setArticle( ArticleEntity article ) {
        this.article = article;
    }
    public ArticleEntity getArticle() {
        return this.article;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(qte);
        return sb.toString(); 
    } 

}
