/*
 * Created on 31 oct. 2017 ( Time 18:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "RESSOURCE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RESSOURCE", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RessourceEntity.countAll", query="SELECT COUNT(x) FROM RessourceEntity x" )
} )
public class RessourceEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="NSERIE", nullable=false)
    private Integer    nserie       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", length=20)
    private String     nom          ;

    @Column(name="DESCRIPTION", length=256)
    private String     description  ;

    @Column(name="LOCALISATION", length=20)
    private String     localisation ;

	// "responsable" (column "RESPONSABLE") is not defined by itself because used as FK in a link 
	// "type" (column "TYPE") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="TYPE", referencedColumnName="TYPE")
    private TypeRessourceEntity typeRessource;

    @OneToMany(mappedBy="ressource2", targetEntity=DatereservationEntity.class)
    private List<DatereservationEntity> listOfDatereservation;

    @ManyToOne
    @JoinColumn(name="RESPONSABLE", referencedColumnName="LOGIN")
    private UtilisateurEntity utilisateur ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RessourceEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNserie( Integer nserie ) {
        this.nserie = nserie ;
    }
    public Integer getNserie() {
        return this.nserie;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : LOCALISATION ( VARCHAR ) 
    public void setLocalisation( String localisation ) {
        this.localisation = localisation;
    }
    public String getLocalisation() {
        return this.localisation;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTypeRessource( TypeRessourceEntity typeRessource ) {
        this.typeRessource = typeRessource;
    }
    public TypeRessourceEntity getTypeRessource() {
        return this.typeRessource;
    }

    public void setListOfDatereservation( List<DatereservationEntity> listOfDatereservation ) {
        this.listOfDatereservation = listOfDatereservation;
    }
    public List<DatereservationEntity> getListOfDatereservation() {
        return this.listOfDatereservation;
    }

    public void setUtilisateur( UtilisateurEntity utilisateur ) {
        this.utilisateur = utilisateur;
    }
    public UtilisateurEntity getUtilisateur() {
        return this.utilisateur;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(nserie);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(localisation);
        return sb.toString(); 
    } 

}
