/*
 * Created on 3 nov. 2017 ( Time 10:20:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "STOCK"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="STOCK", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StockEntity.countAll", query="SELECT COUNT(x) FROM StockEntity x" )
} )
public class StockEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ARTICLEREF", nullable=false)
    private Integer    articleref   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="QTE")
    private Integer    qte          ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ARTICLEREF", referencedColumnName="REF", insertable=false, updatable=false)
    private ArticleEntity article     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StockEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setArticleref( Integer articleref ) {
        this.articleref = articleref ;
    }
    public Integer getArticleref() {
        return this.articleref;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : QTE ( INTEGER ) 
    public void setQte( Integer qte ) {
        this.qte = qte;
    }
    public Integer getQte() {
        return this.qte;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setArticle( ArticleEntity article ) {
        this.article = article;
    }
    public ArticleEntity getArticle() {
        return this.article;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(articleref);
        sb.append("]:"); 
        sb.append(qte);
        return sb.toString(); 
    } 

}
