/*
 * Created on 31 oct. 2017 ( Time 18:39:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "TYPE_RESSOURCE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="TYPE_RESSOURCE", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TypeRessourceEntity.countAll", query="SELECT COUNT(x) FROM TypeRessourceEntity x" )
} )
public class TypeRessourceEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="TYPE", nullable=false, length=20)
    private String     type         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="typeRessource", targetEntity=RessourceEntity.class)
    private List<RessourceEntity> listOfRessource;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TypeRessourceEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfRessource( List<RessourceEntity> listOfRessource ) {
        this.listOfRessource = listOfRessource;
    }
    public List<RessourceEntity> getListOfRessource() {
        return this.listOfRessource;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(type);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
