/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.ArticleEntity;
import org.demo.mock.ArticleEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.ArticlePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Article persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Article persistence : delete + load ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		
		ArticleEntityMock mock = new ArticleEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(ArticlePersistence service, ArticleEntityMock mock, Integer ref ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ArticleEntity entity = service.load( ref );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( ref ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( ref );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
