/*
 * Created on 31 oct. 2017 ( Time 18:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.DatereservationEntity;
import org.demo.mock.DatereservationEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.DatereservationPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Datereservation persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class DatereservationPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		DatereservationPersistence service = PersistenceServiceProvider.getService(DatereservationPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Datereservation persistence : delete + load ..." );
		
		DatereservationPersistence service = PersistenceServiceProvider.getService(DatereservationPersistence.class);
		
		DatereservationEntityMock mock = new DatereservationEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(DatereservationPersistence service, DatereservationEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		DatereservationEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Ressource
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
