/*
 * Created on 3 nov. 2017 ( Time 10:21:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.StockEntity;
import org.demo.mock.StockEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.StockPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Stock persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class StockPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		StockPersistence service = PersistenceServiceProvider.getService(StockPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void testGetQteArticle() {
		
		System.out.println("Test GetQteArticle ..." );
		
		StockPersistence service = PersistenceServiceProvider.getService(StockPersistence.class);
		Assert.assertTrue(service.getQteArticle(1) == 20);
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Stock persistence : delete + load ..." );
		
		StockPersistence service = PersistenceServiceProvider.getService(StockPersistence.class);
		
		StockEntityMock mock = new StockEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(StockPersistence service, StockEntityMock mock, Integer articleref ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		StockEntity entity = service.load( articleref );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( articleref ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Article
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( articleref );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
