/*
 * Created on 31 oct. 2017 ( Time 18:39:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.TypeRessourceEntity;
import org.demo.mock.TypeRessourceEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.TypeRessourcePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for TypeRessource persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypeRessourcePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		TypeRessourcePersistence service = PersistenceServiceProvider.getService(TypeRessourcePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test TypeRessource persistence : delete + load ..." );
		
		TypeRessourcePersistence service = PersistenceServiceProvider.getService(TypeRessourcePersistence.class);
		
		TypeRessourceEntityMock mock = new TypeRessourceEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(TypeRessourcePersistence service, TypeRessourceEntityMock mock, String type ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		TypeRessourceEntity entity = service.load( type );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( type ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( type );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
