/*
 * Created on 3 nov. 2017 ( Time 10:21:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.test.persistence;


import org.demo.bean.jpa.UtilisateurEntity;
import org.demo.mock.UtilisateurEntityMock;
import org.demo.persistence.PersistenceServiceProvider;
import org.demo.persistence.services.UtilisateurPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Utilisateur persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class UtilisateurPersistenceTest 
{
	@Test
	public void testLogin() {
		
		System.out.println("Test login ..." );
		
		UtilisateurPersistence service = PersistenceServiceProvider.getService(UtilisateurPersistence.class);
		UtilisateurEntity user = service.login("thomas","1234");
		System.out.println(user.toString());
		UtilisateurEntity user2 = service.login("maurice","1234");
		Assert.assertNotNull(user);
		Assert.assertNull(user2);
	}
	
	@Test
	public void testcheckLogin() {
		
		System.out.println("Test checkLogin ..." );
		
		UtilisateurPersistence service = PersistenceServiceProvider.getService(UtilisateurPersistence.class);
		boolean b = service.checkLogin("thomas");
		boolean b2 = service.checkLogin("maurice");
		Assert.assertTrue(b);
		Assert.assertFalse(b2);
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Utilisateur persistence : delete + load ..." );
		
		UtilisateurPersistence service = PersistenceServiceProvider.getService(UtilisateurPersistence.class);
		
		UtilisateurEntityMock mock = new UtilisateurEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(UtilisateurPersistence service, UtilisateurEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		UtilisateurEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
