
/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.ArticleEntity;
import org.demo.mock.tool.MockValues;

public class ArticleEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ArticleEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ArticleEntity createInstance( Integer ref ) {
		ArticleEntity entity = new ArticleEntity();
		// Init Primary Key fields
		entity.setRef( ref) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(200) ) ; // java.lang.String 
		entity.setPrix( mockValues.nextFloat() ) ; // java.lang.Float 
		// Init Link fields (if any)
		// setListOfStock( TODO ) ; // List<Stock> 
		// setListOfPanieritem( TODO ) ; // List<Panieritem> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ArticleEntity> createList(int count) {
		List<ArticleEntity> list = new LinkedList<ArticleEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
