
/*
 * Created on 31 oct. 2017 ( Time 18:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.DatereservationEntity;
import org.demo.mock.tool.MockValues;

public class DatereservationEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public DatereservationEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public DatereservationEntity createInstance( Integer id ) {
		DatereservationEntity entity = new DatereservationEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setDebut( mockValues.nextDate() ) ; // java.util.Date 
		entity.setFin( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setRessource2( TODO ) ; // Ressource 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<DatereservationEntity> createList(int count) {
		List<DatereservationEntity> list = new LinkedList<DatereservationEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
