
/*
 * Created on 3 nov. 2017 ( Time 10:20:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.PanieritemEntity;
import org.demo.mock.tool.MockValues;

public class PanieritemEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PanieritemEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PanieritemEntity createInstance( Integer id ) {
		PanieritemEntity entity = new PanieritemEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setQte( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setUtilisateur( TODO ) ; // Utilisateur 
		// setArticle( TODO ) ; // Article 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PanieritemEntity> createList(int count) {
		List<PanieritemEntity> list = new LinkedList<PanieritemEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
