
/*
 * Created on 31 oct. 2017 ( Time 18:39:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.RessourceEntity;
import org.demo.mock.tool.MockValues;

public class RessourceEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RessourceEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RessourceEntity createInstance( Integer nserie ) {
		RessourceEntity entity = new RessourceEntity();
		// Init Primary Key fields
		entity.setNserie( nserie) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setDescription( mockValues.nextString(256) ) ; // java.lang.String 
		entity.setLocalisation( mockValues.nextString(20) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setTypeRessource( TODO ) ; // TypeRessource 
		// setListOfDatereservation( TODO ) ; // List<Datereservation> 
		// setUtilisateur( TODO ) ; // Utilisateur 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RessourceEntity> createList(int count) {
		List<RessourceEntity> list = new LinkedList<RessourceEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
