
/*
 * Created on 31 oct. 2017 ( Time 18:39:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.TypeRessourceEntity;
import org.demo.mock.tool.MockValues;

public class TypeRessourceEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TypeRessourceEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(20) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TypeRessourceEntity createInstance( String type ) {
		TypeRessourceEntity entity = new TypeRessourceEntity();
		// Init Primary Key fields
		entity.setType( type) ;
		// Init Data fields
		// Init Link fields (if any)
		// setListOfRessource( TODO ) ; // List<Ressource> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TypeRessourceEntity> createList(int count) {
		List<TypeRessourceEntity> list = new LinkedList<TypeRessourceEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
