
/*
 * Created on 31 oct. 2017 ( Time 18:39:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.UtilisateurEntity;
import org.demo.mock.tool.MockValues;

public class UtilisateurEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UtilisateurEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(20) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UtilisateurEntity createInstance( String login ) {
		UtilisateurEntity entity = new UtilisateurEntity();
		// Init Primary Key fields
		entity.setLogin( login) ;
		// Init Data fields
		entity.setPassword( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setNom( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setPrenom( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setMail( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setTel( mockValues.nextString(10) ) ; // java.lang.String 
		entity.setType( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setListOfRessource( TODO ) ; // List<Ressource> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UtilisateurEntity> createList(int count) {
		List<UtilisateurEntity> list = new LinkedList<UtilisateurEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
