/*
 * Created on 3 nov. 2017 ( Time 10:20:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.persistence.services;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.ArticleEntity;

/**
 * Basic persistence operations for entity "Article"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface ArticlePersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param article
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(ArticleEntity article) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param ref
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer ref) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param article
	 */
	public void insert(ArticleEntity article) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param ref
	 * @return the entity loaded (or null if not found)
	 */
	public ArticleEntity load(Integer ref) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<ArticleEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<ArticleEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<ArticleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param article
	 * @return
	 */
	public ArticleEntity save(ArticleEntity article) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<ArticleEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
